### ISSUE TITLE
Comments should be always visible [WEB122]

### ISSUE THREAD

**Issue by firebird-automations** [FirebirdSQL/web#112]
Submitted by: @WarmBooter

Assigned to: @alexeykovyazin

I think the comments in the official site's pages should be visible by default \(not requiring a click to appear\)\. This would probably grow the interactivity and interest for the site\.

**Comment by firebird-automations** [comment]
Commented by: @mrotteveel

I'd suggest the comment feature should be removed entirely\. I don't think they are really useful, and without a proper notification system it looks bad if there is no response to comments\.

**Comment by firebird-automations** [comment]
Commented by: @WarmBooter

The actual comments are handled by facebook, so notification depends on your settings\.

**Comment by firebird-automations** [comment]
Commented by: @mrotteveel

Which settings? As far as I can tell I can't "subscribe" to a page to be notified when comments are posted\.

**Comment by firebird-automations** [comment]
Commented by: @WarmBooter

I don't remember :\( Facebook interface really sucks\. Months ago I was tired of receiving email notifications about such comments and I disabled a lot of things there, and can't remember what ones affected this behavior\.

**Comment by firebird-automations** [comment]
Commented by: @mariuz

facebook comments system sould be replaced with disqus with proper threads and responses for each page and documentation pages 

<https://disqus.com/websites/>

**Comment by mrotteveel** [comment]
The comment system was removed a long time ago.
