### ISSUE TITLE
CLONE -non existin link for "FB/Java" plug-in preliminary test version" [WEB142]

### ISSUE THREAD

**Issue by firebird-automations** [FirebirdSQL/web#130]
Submitted by: akhil p (akhil)

 "FB/Java" plug\-in preliminary test version
<http://www.firebirdsql.org/index.php?op=devel&sub=plugins&id=external_java>    =  ok

so on next page
Download the Fb/Java Plug\-in and server for 32\-bit Windows\.

<http://www.firebirdsql.org/downloads/rabbits/asfernandes/fbjava/fbjava-m1.zip>      = fails
	
Hope this is the place to report this\.
Derryck

**Comment by firebird-automations** [comment]
Commented by: @mrotteveel

Why did you clone [WEB66](https://github.com/FirebirdSQL/web/issues?q=WEB66+in%3Atitle)?

**Comment by mrotteveel** [comment]
Duplicate of #61
