### ISSUE TITLE
Wrong links to the QA resources [WEB148]

### ISSUE THREAD

**Issue by firebird-automations** [FirebirdSQL/web#136]
Submitted by: @hvlad

Assigned to: @alexeykovyazin

Page 
<http://www.firebirdsql.org/en/devel-qa/> 

contains links to the CVS modules 
<http://cvs.sourceforge.net/cgi-bin/viewcvs.cgi/firebird/>

but CVS abandoned for a long time at SF\.

Correct links should point to the SVN repository 
<http://svn.code.sf.net/p/firebird/code/qa/>

**Comment by firebird-automations** [comment]
Commented by: @hvlad

Oops, sorry, looks like it is duplicate of [WEB147](https://github.com/FirebirdSQL/web/issues?q=WEB147+in%3Atitle)

**Comment by mrotteveel** [comment]
The page was fixed (probably during the migration to GitHub).
