### ISSUE TITLE
www.netpnb.com [WEB149]

### ISSUE THREAD

**Issue by firebird-automations** [FirebirdSQL/web#137]
Submitted by: suneel kumar (suneel.jsi1)

Assigned to: @alexeykovyazin

Attachments:
[oramon.exe](https://github.com/FirebirdSQL/jira-attachments-private/raw/main/WEB/WEB-149/12985_oramon.exe)
[Firebird_ODBC_2.0.4.155_Win32.exe](https://github.com/FirebirdSQL/jira-attachments-private/raw/main/WEB/WEB-149/12986_Firebird_ODBC_2.0.4.155_Win32.exe)
[brie.exe](https://github.com/FirebirdSQL/jira-attachments-private/raw/main/WEB/WEB-149/12987_brie.exe)

login automaticaly

**Comment by firebird-automations** [comment]
<details><summary>Modified by: suneel kumar (suneel.jsi1)</summary>

Attachment: oramon\.exe \[ 12985 \]

Attachment: Firebird\_ODBC\_2\.0\.4\.155\_Win32\.exe \[ 12986 \]

Attachment: brie\.exe \[ 12987 \]
</details>

**Comment by mariuz** [comment]
this i guess can be closed
