### ISSUE TITLE
Sorting by column in "Watches" and "Votes" [WEB160]

### ISSUE THREAD

**Issue by firebird-automations** [FirebirdSQL/web#146]
Submitted by: @livius2

Assigned to: @alexeykovyazin

After login to the tracker we have on the right 
My Unresolved Reported Issues \| Watches \| Votes

and "My Unresolved Reported Issues" have sorting by column
but Watches and Votes doesn't\. Please add sorting there\.

**Comment by mrotteveel** [comment]
No longer relevant after migration to GitHub issues
