### ISSUE TITLE
Add HTTPs support for tracker website [WEB161]

### ISSUE THREAD

**Issue by firebird-automations** [FirebirdSQL/web#147]
Submitted by: Lucas Schatz (arvanus)

Assigned to: @alexeykovyazin

Jira\_subtask\_outward [WEB167](https://github.com/FirebirdSQL/web/issues?q=WEB167+in%3Atitle)

Votes: 2

Please, take a look at "Let's Encrypt" project, it offers a totally free SSL certificate to use in your website, easily  integrated into Apache and Nginx webservers\.

Here you can take a look at the project's site, and it's documentation:
<https://letsencrypt.org/>
<https://letsencrypt.org/getting-started/>

If any administrator could take a moment to analyze it, every user will be benefited\.
Thanks\!

**Comment by firebird-automations** [comment]
Commented by: @mariuz

I voted for this , now passwords are sent in clear text and can be sniffed on this site

**Comment by mrotteveel** [comment]
No longer relevant after migration to GitHub issues
