### ISSUE TITLE
RSS Feed doesn't validate [WEB163]

### ISSUE THREAD

**Issue by firebird-automations** [FirebirdSQL/web#149]
Submitted by: @mariuz

Assigned to: @alexeykovyazin

RSS Feed doesn't validate

<https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.firebirdsql.org%2Frss%2Fen%2Fnews.xml>

**Comment by mrotteveel** [comment]
Asked Sergey to fix this, and it has been fixed.
