### ISSUE TITLE
The Firebird SQL website feed does not conform to the W3C standard

### ISSUE THREAD

**Issue by luronumen** [FirebirdSQL/web#158]
**ACTUAL RESULT**
- The Firebird SQL website feed does not conform to the W3C standard

**EXPECTED RESULT**
- The Firebird SQL site feed should conform to the W3C standard

**STEPS TO REPRODUCE THE ISSUE**

1.  Open the [W3C Feed Validation Service](https://validator.w3.org/feed/) website and che the [Firebird SQL website feed](https://www.firebirdsql.org/rss/en/news.xml): Verify that several errors are found in the [Firebird SQL website feed](https://www.firebirdsql.org/rss/en/news.xml).

**Comment by mrotteveel** [comment]
Duplicates: #149

**Comment by luronumen** [comment]
Thank you very much for the fix!

Best Regards,
Luciano
