### ISSUE TITLE
security image is missing on the subscribe form 

### ISSUE THREAD

**Issue by mariuz** [FirebirdSQL/web#164]
On https://firebirdsql.org/en/subscribe/

img src should be without dfp in front 

![image](https://user-images.githubusercontent.com/18359/233603214-d05503d0-d9dc-4718-880d-8a443bca4333.png)

**Comment by mrotteveel** [comment]
This page is not in the CMS, so it seems to be generated somewhere else. I'll contact Sergey if he knows about this.

The "Newsletter" block shown on some pages also links to dfp.firebirdsql.org, so I guess the problem is bigger than just this.

**Comment by Greendq** [comment]
Should work now. DNS record lost during DNS upgrade.
