### ISSUE TITLE
Broken redirect from old CORE addresses to appropriate GH ones

### ISSUE THREAD

**Issue by pavel-zotov** [FirebirdSQL/web#165]
Try to jump to old CORE:
http://tracker.firebirdsql.org/browse/core-5020
 
You will see:
https://github.com/FirebirdSQL
 
Expected:
https://github.com/FirebirdSQL/firebird/issues/5308

**Comment by mrotteveel** [comment]
@cincuranet In case you didn't see this one.

**Comment by cincuranet** [comment]
That's expected. The proper URL is http://tracker.firebirdsql.org/browse/CORE-5020.

**Comment by pavel-zotov** [comment]
Just out of curiosity: since what time one need to take in account case of letters for that ("CORE" rather than "core") ?
I can't get rid of the assumption that it was not so before (e.g. 1or 2 years ago)
